### ISSUE TITLE
Data is not in the right columns

### ISSUE THREAD

**Issue by LoveMyData** [MichaelBone/city_of_west_torrens_sa_development_applications#1]
Looking at data collected on morph's csv output line 10, 11 to more recent line 138. There are some incorrect data in info_url column.

**Comment by MichaelBone** [comment]
thanks, yes … wasn't originally sure what to do there (the query string for each development application URL was just an index number that was meaningless outside the context of the original search), but I think I've got a workable solution now … I've just checked it in.

**Comment by MichaelBone** [comment]
Actually, just copied one of those constructed information URLs to another computer and it fails:

https://ecouncil.mountgambier.sa.gov.au/eservice/daEnquiry.do?number=220%2F2018

So I'm not sure there is a way around it.  The above URL only seems to work if you've already navigated to the https://ecouncil.mountgambier.sa.gov.au/eservice site and done a search.  If not, you get the exception included below.  So not sure what to do about that (maybe it's better than nothing, though).

Error Page Exception
SRVE0260E: The server cannot use the error page specified for your application to handle the Original Exception printed below.

Original Exception:
Error Message: java.lang.AssertionError: Must have a UserContainer object
Error Code: 500
Target Servlet: 
Error Stack: 
java.lang.AssertionError: Must have a UserContainer object 
     at au.com.civica.eservices.register.logic.RegisterEnquiryResultsXMLBuilder.buildXML(RegisterEnquiryResultsXMLBuilder.java:116) 
     at au.com.civica.eservices.document.struts.DAXMLAction.execute(DAXMLAction.java:42) 
     at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:421) 
     at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:226) 
...

**Comment by LoveMyData** [comment]
Well, you can't really get away with this one because of cookie

**Comment by LoveMyData** [comment]
In this case, I will link the info_url to the council's main DA page so users can type in the DA number by themselves.

**Comment by MichaelBone** [comment]
Changed the scraper to use a hard-coded URL to the council's main DA search page as suggested.
